---
is_node_exporter_enabled: true
is_ssh_keys_enabled: true
ssh_keys_install_private_for_ansible_user: false
ssh_keys_install_public_for_ansible_user: false
ssh_keys_install_private_for_root: true
ssh_keys_install_public_for_root: true

