services:

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    networks: [media]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - "8686:8686"
    volumes:
      - /etc/lidarr:/config
      - /mnt/media-acquisition/downloads:/downloads
      - /mnt/media-acquisition/music:/music

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks: [media]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - "7878:7878"
    volumes:
      - /etc/radarr:/config
      - /mnt/media-acquisition/downloads:/downloads
      - /mnt/media-acquisition/movies:/movies

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks: [media]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - "8989:8989"
    volumes:
      - /etc/sonarr:/config
      - /mnt/media-acquisition/downloads:/downloads
      - /mnt/media-acquisition/tv:/tv

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    networks: [media]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - "9091:9091"
    volumes:
      - /etc/transmission:/config
      - /var/lib/transmission/watch:/watch
      - /mnt/media-acquisition/downloads:/downloads

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /etc/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

networks:
  media: {}