services:
  vaultwarden:
    image: vaultwarden/server:1.34.3
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /var/lib/vaultwarden:/data
    ports:
      - 35550:80
    env_file:
      - ./.env

