---
all:
  hosts:
    arcturus:
      ansible_host: 192.168.86.124
    blaine:
      ansible_host: 192.168.86.223
      gatus_slug: "(OpenVPN Gateway)"
    carrie:
      ansible_host: 192.168.86.228
      gatus_slug: "(Ubuntu Docker/Misc)"
    derry:
      ansible_host: 192.168.86.210
    flagg:
      ansible_host: 192.168.86.205
      gatus_slug: "(Ubuntu Docker/Core)"
    gilead:
      ansible_host: 100.95.108.6
    misery:
      ansible_host: 192.168.86.227
    patricia:
      ansible_host: 192.168.86.224
      gatus_slug: "(Ubuntu Docker/Media)"
    polaris:
      ansible_host: 192.168.86.101
    procyon:
      ansible_host: 192.168.86.106
    sirius:
      ansible_host: 192.168.86.105 

  children:
    fully_managed:
      children:
        ubuntu:
          children:
            docker_compose:
              children:
                docker_compose_monitoring:
                  children:
                    docker_compose_it_tools:
                      hosts:
                        carrie:
                    docker_compose_media_acquisition:
                      hosts:
                        patricia:
                    docker_compose_memos:
                      hosts:
                        carrie:
                    docker_compose_ngb:
                      hosts:
                        carrie:
            ubuntu_misc:
              hosts:
                carrie:
                patricia:
            ubuntu_openvpn:
              hosts:
                blaine:
    semi_managed:
      children:
        ubuntu:
          children:
            docker_compose:
              children:
                docker_compose_monitoring:
                  children:
                    docker_compose_cloudflare:
                      hosts:
                        flagg:
                    docker_compose_gatus:
                      hosts:
                        flagg:
                    docker_compose_pihole:
                      hosts:
                        flagg:
                    docker_compose_traefik:
                      hosts:
                        flagg:
                    docker_compose_twingate:
                      hosts:
                        flagg:
            ubuntu_core:
              hosts:
                flagg:
    unmanaged:
      hosts:
        gilead:
        polaris:
        sirius:

