---
arch_base_packages:
  - python
  - ca-certificates
  - openssh
  - curl
  - jq
  - git
  - vim
  - htop
  - unzip
  - tar
  - cmatrix
  - fastfetch
  - stow
  - zsh
  - starship
  - neovim
  - bind
  - rsync
  - less
  - base-devel

arch_base_enable_timesyncd: true
arch_base_timezone: "{{ gitops_tz | default('America/New_York') }}"
arch_base_journald_persistent: true
