name: devops b - template builder

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

concurrency:
  group: gitops-homelab-orchestrator-${{ github.ref }}
  cancel-in-progress: true

jobs:
  template-builder:
    timeout-minutes: 20
    environment: lab
    runs-on:
      - self-hosted
      - Linux
      - X64

    env:
      ## required for proxmox host access
      PVE_ACCESS_HOST:   ${{ secrets.PVE_ACCESS_HOST }}
      PM_TOKEN_ID:       ${{ secrets.PM_TOKEN_ID }}
      PM_TOKEN_SECRET:   ${{ secrets.PM_TOKEN_SECRET }}
      PVE_NODE:          ${{ secrets.PVE_NODE }}

      ## disable doppler in makefile
      CI: "true"
      DOPPLER: "0"

    steps:
      ## prepare the local runner environment
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3

      ## sanity check that proxmox is ready
      - name: Proxmox validations
        run: |
          set -euo pipefail
          make l0-runway

      ## build template using packer and export manifest
      - name: Packer init and validate
        run: |
          set -euo pipefail
          make l1-init
          make l1-validate

      - name: Packer build
        run: |
          set -euo pipefail
          make l1-build

      - name: Create manifest
        run: |
          set -euo pipefail
          make l1-manifest

      - name: List artifacts
        run: ls -lah artifacts/l1_images

      ## Upload manifest artifacts
      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: template-builder-artifacts
          path: artifacts/l1_images
          retention-days: 28
          if-no-files-found: error
