name: devops d - converge only

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

concurrency:
  group: devops-${{ github.ref }}
  cancel-in-progress: true

jobs:
  converge-only:
    timeout-minutes: 20
    environment: lab
    runs-on:
      - self-hosted
      - Linux
      - X64

    env:
      ## required for proxmox host access
      PVE_ACCESS_HOST:                ${{ secrets.PVE_ACCESS_HOST }}
      PM_TOKEN_ID:                    ${{ secrets.PM_TOKEN_ID }}
      PM_TOKEN_SECRET:                ${{ secrets.PM_TOKEN_SECRET }}
      PVE_NODE:                       ${{ secrets.PVE_NODE }}
      PVE_STORAGE_VM:                 ${{ secrets.PVE_STORAGE_VM }}
      ## disable doppler in makefile
      CI: "true"
      DOPPLER: "0"

    steps:
      ## log local runner information
      - name: Identify runner
        run: |
          echo "Runner: $RUNNER_NAME"
          echo "Host: $(hostname)"
          echo "User: $(whoami)"

      ## prepare the local runner environment
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH key for Ansible
        run: |
          set -euo pipefail

          mkdir -p "$HOME/.ssh"
          chmod 700 "$HOME/.ssh"

          cat << 'EOF' > "$HOME/.ssh/id_ed25519"
          ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          EOF

          chmod 600 "$HOME/.ssh/id_ed25519"
          echo "SSH key configured."

      ## sanity check that proxmox is ready
      - name: Proxmox validations
        run: |
          set -euo pipefail
          make l0-runway
